freebsd_instance:
  image_family: freebsd-13-0
ci_task:
  install_script: |
    pkg install -y go
  vet_script: |
    go vet ./...
  test_script: |
    go test -v ./...
    go test -v -race ./...
    go test -v -gcflags=all=-d=checkptr ./...
