name: ci
on:
  push:
    branches:
      - johejo/main # TODO(johejo): Temporary
  pull_request:
    branches:
      - johejo/main # TODO(johejo): Temporary
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - "1.15.x"
          - "1.16.x"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test -v ./...
      - run: |
          go test -v -race ./...
      - run: |
          go test -v -gcflags=all=-d=checkptr ./...
